/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback
         * @description Finish the login: exchange the code, create the session, set the cookie.
         */
        get: operations["callback_api_v1_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login
         * @description Start the login: redirect to the identity provider.
         */
        get: operations["login_api_v1_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the HSP session and return the identity provider's logout URL.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who is logged in, plus the CSRF token for state-changing requests.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Buildings */
        get: operations["list_buildings_api_v1_buildings_get"];
        put?: never;
        /** Create Building */
        post: operations["create_building_api_v1_buildings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{building_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Building */
        get: operations["get_building_api_v1_buildings__building_id__get"];
        put?: never;
        post?: never;
        /**
         * Archive Building
         * @description Archive (soft delete). Refused with 409 while active floors exist (docs/0078).
         */
        delete: operations["archive_building_api_v1_buildings__building_id__delete"];
        options?: never;
        head?: never;
        /** Update Building */
        patch: operations["update_building_api_v1_buildings__building_id__patch"];
        trace?: never;
    };
    "/api/v1/buildings/{building_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Building
         * @description Refused with 409 while the site is archived: restore top-down (docs/0078).
         */
        post: operations["restore_building_api_v1_buildings__building_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/floors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Floors */
        get: operations["list_floors_api_v1_floors_get"];
        put?: never;
        /** Create Floor */
        post: operations["create_floor_api_v1_floors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/floors/{floor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Floor */
        get: operations["get_floor_api_v1_floors__floor_id__get"];
        put?: never;
        post?: never;
        /** Archive Floor */
        delete: operations["archive_floor_api_v1_floors__floor_id__delete"];
        options?: never;
        head?: never;
        /** Update Floor */
        patch: operations["update_floor_api_v1_floors__floor_id__patch"];
        trace?: never;
    };
    "/api/v1/floors/{floor_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Draft
         * @description The current draft plan with its revision counter (admins only, docs/0080).
         */
        get: operations["get_draft_api_v1_floors__floor_id__draft_get"];
        put?: never;
        /**
         * Create Draft
         * @description Start a draft explicitly. Usually unnecessary: the first changeset starts one (docs/0081).
         */
        post: operations["create_draft_api_v1_floors__floor_id__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/floors/{floor_id}/draft/changesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Changeset
         * @description Apply a batch of add/update/delete operations to the draft, all or nothing.
         *
         *     409 stale-revision if `base_revision` is outdated, 409 lock-required / 423 floor-locked
         *     without the edit lock, 422 changeset-invalid with per-operation errors.
         */
        post: operations["apply_changeset_api_v1_floors__floor_id__draft_changesets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/floors/{floor_id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lock Status
         * @description Who is editing this floor, if anyone.
         */
        get: operations["lock_status_api_v1_floors__floor_id__lock_get"];
        put?: never;
        /**
         * Acquire Lock
         * @description Acquire the lock, or extend your own (heartbeat). 423 if someone else is editing.
         */
        post: operations["acquire_lock_api_v1_floors__floor_id__lock_post"];
        /**
         * Release Lock
         * @description Release your own lock. Idempotent; 409 if someone else holds it.
         */
        delete: operations["release_lock_api_v1_floors__floor_id__lock_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/floors/{floor_id}/lock/force-release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force Release Lock
         * @description Admin override: remove whoever's lock. Their draft is kept. Audited.
         */
        post: operations["force_release_lock_api_v1_floors__floor_id__lock_force_release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/floors/{floor_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Floor
         * @description Refused with 409 while the building is archived: restore top-down (docs/0078).
         */
        post: operations["restore_floor_api_v1_floors__floor_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/floors/{floor_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description Version history, oldest first. Viewers see published and superseded versions only.
         *
         *     Uses the standard list envelope (docs/0040); history is returned in one page for now
         *     (`next_cursor` is always null), so cursor paging can be added without breaking clients.
         */
        get: operations["list_versions_api_v1_floors__floor_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/floors/{floor_id}/versions/{a}/diff/{b}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diff Versions
         * @description What changed from version a to version b: added, removed, and changed fields.
         */
        get: operations["diff_versions_api_v1_floors__floor_id__versions__a__diff__b__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/floors/{floor_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description The complete plan of one version (docs/0036), with the catalog items it uses.
         */
        get: operations["get_version_api_v1_floors__floor_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sites */
        get: operations["list_sites_api_v1_sites_get"];
        put?: never;
        /** Create Site */
        post: operations["create_site_api_v1_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site */
        get: operations["get_site_api_v1_sites__site_id__get"];
        put?: never;
        post?: never;
        /**
         * Archive Site
         * @description Archive (soft delete). Refused with 409 while active buildings exist (docs/0078).
         */
        delete: operations["archive_site_api_v1_sites__site_id__delete"];
        options?: never;
        head?: never;
        /** Update Site */
        patch: operations["update_site_api_v1_sites__site_id__patch"];
        trace?: never;
    };
    "/api/v1/sites/{site_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Site */
        post: operations["restore_site_api_v1_sites__site_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description The process is alive.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description The service can handle traffic: the database is reachable.
         *
         *     TODO: also verify the Alembic schema revision and Keycloak reachability (docs/0056, 0057).
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddOp */
        AddOp: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             * @description Client-generated UUIDv7 (docs/0035)
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "wall" | "opening" | "column" | "zone" | "object";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add";
        };
        /** BuildingIn */
        BuildingIn: {
            /**
             * Code
             * @description Short code, unique within the site (e.g. A, HQ-1)
             */
            code: string;
            /** Name */
            name: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
        };
        /** BuildingOut */
        BuildingOut: {
            /** Archived At */
            archived_at: string | null;
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BuildingPatch */
        BuildingPatch: {
            /** Code */
            code?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * CatalogItem
         * @description A catalog item revision used by the plan, embedded so the editor needs no extra calls.
         */
        CatalogItem: {
            /** Attaches To Categories */
            attaches_to_categories: string[];
            /** Category */
            category: string;
            /** Color */
            color: string | null;
            /** Depth Mm */
            depth_mm: number;
            /** Footprint Blocks */
            footprint_blocks: boolean;
            /** Height Mm */
            height_mm: number;
            /**
             * Id
             * Format: uuid
             * @description catalog_item_rev id (what objects reference)
             */
            id: string;
            /** Is Seat */
            is_seat: boolean;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Key */
            key: string;
            /** Mountable */
            mountable: boolean;
            /** Name */
            name: string;
            /**
             * Shape
             * @enum {string}
             */
            shape: "box" | "cylinder" | "l_shape" | "model";
            /** Width Mm */
            width_mm: number;
        };
        /** ChangesetIn */
        ChangesetIn: {
            /**
             * Base Revision
             * @description The draft revision the client edited (0 = new)
             */
            base_revision: number;
            /** Ops */
            ops: (components["schemas"]["AddOp"] | components["schemas"]["UpdateOp"] | components["schemas"]["DeleteOp"])[];
        };
        /** ChangesetResult */
        ChangesetResult: {
            /** Cascaded */
            cascaded: {
                [key: string]: unknown;
            }[];
            /**
             * Floor Id
             * Format: uuid
             */
            floor_id: string;
            /** Revision */
            revision: number;
            /** Version */
            version: number;
            /**
             * Warnings
             * @default []
             */
            warnings: {
                [key: string]: unknown;
            }[];
        };
        /** Column */
        Column: {
            /** Footprint */
            footprint: [
                number,
                number
            ][];
            /** Height Mm */
            height_mm: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** DeleteOp */
        DeleteOp: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "wall" | "opening" | "column" | "zone" | "object";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "delete";
        };
        /** ElementChange */
        ElementChange: {
            /**
             * After
             * @description The same fields, as in version b
             */
            after: {
                [key: string]: unknown;
            };
            /**
             * Before
             * @description Only the fields that differ, as in version a
             */
            before: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** FloorIn */
        FloorIn: {
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /**
             * Default Wall Height Mm
             * @description Millimetres
             * @default 2800
             */
            default_wall_height_mm: number;
            /**
             * Elevation Mm
             * @description Millimetres (docs/0029)
             * @default 0
             */
            elevation_mm: number;
            /**
             * Level Index
             * @description 0 = ground; negative = basement
             */
            level_index: number;
            /** Name */
            name: string;
            /**
             * Origin X Mm
             * @description Millimetres (docs/0029)
             * @default 0
             */
            origin_x_mm: number;
            /**
             * Origin Y Mm
             * @description Millimetres (docs/0029)
             * @default 0
             */
            origin_y_mm: number;
        };
        /** FloorOut */
        FloorOut: {
            /** Archived At */
            archived_at: string | null;
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Wall Height Mm */
            default_wall_height_mm: number;
            /** Elevation Mm */
            elevation_mm: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Level Index */
            level_index: number;
            /** Name */
            name: string;
            /** Origin X Mm */
            origin_x_mm: number;
            /** Origin Y Mm */
            origin_y_mm: number;
            /**
             * Published Version
             * @description Null until the first publish (docs/0015)
             */
            published_version: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FloorPatch */
        FloorPatch: {
            /** Default Wall Height Mm */
            default_wall_height_mm?: number | null;
            /** Elevation Mm */
            elevation_mm?: number | null;
            /** Level Index */
            level_index?: number | null;
            /** Name */
            name?: string | null;
            /** Origin X Mm */
            origin_x_mm?: number | null;
            /** Origin Y Mm */
            origin_y_mm?: number | null;
        };
        /** FloorVersion */
        FloorVersion: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Note */
            note: string | null;
            /** Published At */
            published_at: string | null;
            /** Published By */
            published_by: string | null;
            /**
             * Revision
             * @description Draft revision counter, bumped per changeset (docs/0036)
             */
            revision: number;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "published" | "superseded" | "discarded";
            /** Version */
            version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** KindDiff */
        KindDiff: {
            /**
             * Added
             * @description Full elements present only in b
             * @default []
             */
            added: {
                [key: string]: unknown;
            }[];
            /**
             * Changed
             * @default []
             */
            changed: components["schemas"]["ElementChange"][];
            /**
             * Removed
             * @description Full elements present only in a
             * @default []
             */
            removed: {
                [key: string]: unknown;
            }[];
        };
        /** LockStatus */
        LockStatus: {
            /** Acquired At */
            acquired_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Floor Id
             * Format: uuid
             */
            floor_id: string;
            /** Holder Name */
            holder_name?: string | null;
            /** Holder Subject */
            holder_subject?: string | null;
            /**
             * Is Mine
             * @default false
             */
            is_mine: boolean;
            /** Locked */
            locked: boolean;
        };
        /** LogoutResult */
        LogoutResult: {
            /** Logout Url */
            logout_url: string | null;
        };
        /** Me */
        Me: {
            /** Csrf Token */
            csrf_token: string;
            /** Email */
            email: string | null;
            /** Is Admin */
            is_admin: boolean;
            /** Name */
            name: string | null;
            /** Roles */
            roles: string[];
            /** Subject */
            subject: string;
        };
        /** Opening */
        Opening: {
            /** Height Mm */
            height_mm: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset Mm */
            offset_mm: number;
            /**
             * Sill Mm
             * @default 0
             */
            sill_mm: number;
            /**
             * Swing
             * @enum {string}
             */
            swing: "left_in" | "left_out" | "right_in" | "right_out" | "sliding" | "none";
            /**
             * Type
             * @enum {string}
             */
            type: "door" | "window";
            /**
             * Wall Id
             * Format: uuid
             */
            wall_id: string;
            /** Width Mm */
            width_mm: number;
        };
        /** Page[BuildingOut] */
        Page_BuildingOut_: {
            /** Items */
            items: components["schemas"]["BuildingOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[FloorOut] */
        Page_FloorOut_: {
            /** Items */
            items: components["schemas"]["FloorOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[FloorVersion] */
        Page_FloorVersion_: {
            /** Items */
            items: components["schemas"]["FloorVersion"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[SiteOut] */
        Page_SiteOut_: {
            /** Items */
            items: components["schemas"]["SiteOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** PlacedObject */
        PlacedObject: {
            /** Allocation Mode */
            allocation_mode?: ("assigned" | "bookable" | "unavailable") | null;
            /** Attached To */
            attached_to?: string | null;
            /**
             * Catalog Item Rev Id
             * Format: uuid
             */
            catalog_item_rev_id: string;
            /** Device Id */
            device_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label?: string | null;
            /** Position */
            position: [
                number,
                number,
                number
            ];
            /**
             * Rotation Ddeg
             * @description Decidegrees, counter-clockwise
             * @default 0
             */
            rotation_ddeg: number;
        };
        /** Plan */
        Plan: {
            /**
             * Catalog
             * @default {}
             */
            catalog: {
                [key: string]: components["schemas"]["CatalogItem"];
            };
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["Column"][];
            /**
             * Floor Id
             * Format: uuid
             */
            floor_id: string;
            /**
             * Objects
             * @default []
             */
            objects: components["schemas"]["PlacedObject"][];
            /**
             * Openings
             * @default []
             */
            openings: components["schemas"]["Opening"][];
            /** Revision */
            revision: number;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "published" | "superseded" | "discarded";
            /** Version */
            version: number;
            /**
             * Walls
             * @default []
             */
            walls: components["schemas"]["Wall"][];
            /**
             * Zones
             * @default []
             */
            zones: components["schemas"]["Zone"][];
        };
        /** PlanDiff */
        PlanDiff: {
            /**
             * @default {
             *       "added": [],
             *       "changed": [],
             *       "removed": []
             *     }
             */
            columns: components["schemas"]["KindDiff"];
            /**
             * Floor Id
             * Format: uuid
             */
            floor_id: string;
            /** From Version */
            from_version: number;
            /**
             * @default {
             *       "added": [],
             *       "changed": [],
             *       "removed": []
             *     }
             */
            objects: components["schemas"]["KindDiff"];
            /**
             * @default {
             *       "added": [],
             *       "changed": [],
             *       "removed": []
             *     }
             */
            openings: components["schemas"]["KindDiff"];
            /** To Version */
            to_version: number;
            /**
             * @default {
             *       "added": [],
             *       "changed": [],
             *       "removed": []
             *     }
             */
            walls: components["schemas"]["KindDiff"];
            /**
             * @default {
             *       "added": [],
             *       "changed": [],
             *       "removed": []
             *     }
             */
            zones: components["schemas"]["KindDiff"];
        };
        /** SiteIn */
        SiteIn: {
            /** Address */
            address?: string | null;
            /** Name */
            name: string;
            /**
             * Time Zone
             * @description IANA time zone, e.g. Europe/Berlin
             */
            time_zone: string;
        };
        /** SiteOut */
        SiteOut: {
            /** Address */
            address: string | null;
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Time Zone */
            time_zone: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SitePatch */
        SitePatch: {
            /** Address */
            address?: string | null;
            /** Name */
            name?: string | null;
            /** Time Zone */
            time_zone?: string | null;
        };
        /** UpdateOp */
        UpdateOp: {
            /**
             * Data
             * @description Only the fields that change
             */
            data: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "wall" | "opening" | "column" | "zone" | "object";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "update";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Wall */
        Wall: {
            /** A */
            a: [
                number,
                number
            ];
            /** B */
            b: [
                number,
                number
            ];
            /** Height Mm */
            height_mm: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Thickness Mm */
            thickness_mm: number;
        };
        /** Zone */
        Zone: {
            /**
             * Boundary
             * @description Polygon vertices, not repeating the first point
             */
            boundary: [
                number,
                number
            ][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Parent Zone Id */
            parent_zone_id?: string | null;
            /**
             * Zone Type Id
             * Format: uuid
             */
            zone_type_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    callback_api_v1_auth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
                error_description?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_get: {
        parameters: {
            query?: {
                /** @description Relative path to return to */
                next?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResult"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    list_buildings_api_v1_buildings_get: {
        parameters: {
            query?: {
                site_id?: string | null;
                include_archived?: boolean;
                /** @description Page size */
                limit?: number;
                /** @description `next_cursor` from the previous page */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BuildingOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_building_api_v1_buildings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_building_api_v1_buildings__building_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                building_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_building_api_v1_buildings__building_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                building_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_building_api_v1_buildings__building_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                building_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_building_api_v1_buildings__building_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                building_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_floors_api_v1_floors_get: {
        parameters: {
            query?: {
                building_id?: string | null;
                include_archived?: boolean;
                /** @description Page size */
                limit?: number;
                /** @description `next_cursor` from the previous page */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FloorOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_floor_api_v1_floors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FloorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_floor_api_v1_floors__floor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_floor_api_v1_floors__floor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_floor_api_v1_floors__floor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FloorPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_v1_floors__floor_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_api_v1_floors__floor_id__draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_changeset_api_v1_floors__floor_id__draft_changesets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangesetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesetResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_status_api_v1_floors__floor_id__lock_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acquire_lock_api_v1_floors__floor_id__lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_lock_api_v1_floors__floor_id__lock_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    force_release_lock_api_v1_floors__floor_id__lock_force_release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_floor_api_v1_floors__floor_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_floors__floor_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FloorVersion_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_versions_api_v1_floors__floor_id__versions__a__diff__b__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
                a: number;
                b: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_floors__floor_id__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floor_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites_api_v1_sites_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
                /** @description Page size */
                limit?: number;
                /** @description `next_cursor` from the previous page */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SiteOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_site_api_v1_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_api_v1_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_site_api_v1_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_site_api_v1_sites__site_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SitePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_site_api_v1_sites__site_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
