"""initial v1 schema (docs/0034)

Creates every v1 table. Extensions: postgis (geometry), btree_gist (version-range exclusion
constraints, docs/0028).

Revision ID: c9b2fc969b7d
Revises:
Create Date: 2026-10-08 11:47:33.934804

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c9b2fc969b7d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - reviewed ###
    op.create_table(
        "tenant",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenant_slug")),
    )
    op.create_table(
        "audit_event",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_subject", sa.String(length=255), nullable=False),
        sa.Column("actor_person_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_audit_event_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index(
        "ix_audit_event_entity",
        "audit_event",
        ["tenant_id", "entity_type", "entity_id", "occurred_at"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_event_tenant_id"), "audit_event", ["tenant_id"], unique=False)
    op.create_table(
        "catalog_item",
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_catalog_item_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_item")),
        sa.UniqueConstraint(
            "tenant_id",
            "key",
            name=op.f("uq_catalog_item_tenant_id_key"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_catalog_item_tenant_id"), "catalog_item", ["tenant_id"], unique=False)
    op.create_table(
        "org_unit",
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("level_label", sa.String(length=100), nullable=True),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "import",
                "ad",
                name="org_unit_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["org_unit.id"], name=op.f("fk_org_unit_parent_id_org_unit")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_org_unit_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_unit")),
        sa.UniqueConstraint(
            "tenant_id", "external_id", name=op.f("uq_org_unit_tenant_id_external_id")
        ),
    )
    op.create_index(op.f("ix_org_unit_parent_id"), "org_unit", ["parent_id"], unique=False)
    op.create_index(op.f("ix_org_unit_tenant_id"), "org_unit", ["tenant_id"], unique=False)
    op.create_index(
        "uq_org_unit_single_root",
        "org_unit",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.create_table(
        "person",
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("idp_subject", sa.String(length=255), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "import",
                "ad",
                name="person_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_person_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person")),
        sa.UniqueConstraint("tenant_id", "email", name=op.f("uq_person_tenant_id_email")),
        sa.UniqueConstraint(
            "tenant_id", "external_id", name=op.f("uq_person_tenant_id_external_id")
        ),
        sa.UniqueConstraint(
            "tenant_id", "idp_subject", name=op.f("uq_person_tenant_id_idp_subject")
        ),
    )
    op.create_index(op.f("ix_person_tenant_id"), "person", ["tenant_id"], unique=False)
    op.create_table(
        "site",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("time_zone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_site_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site")),
    )
    op.create_index(op.f("ix_site_tenant_id"), "site", ["tenant_id"], unique=False)
    op.create_table(
        "user_profile",
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_user_profile_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("subject", name=op.f("pk_user_profile")),
    )
    op.create_index(op.f("ix_user_profile_tenant_id"), "user_profile", ["tenant_id"], unique=False)
    op.create_table(
        "user_session",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("id_token", sa.Text(), nullable=True),
        sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_user_session_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_session_token_hash")),
    )
    op.create_index(
        op.f("ix_user_session_expires_at"), "user_session", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_user_session_subject"), "user_session", ["subject"], unique=False)
    op.create_index(op.f("ix_user_session_tenant_id"), "user_session", ["tenant_id"], unique=False)
    op.create_table(
        "zone_type",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_enclosed", sa.Boolean(), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_zone_type_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone_type")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_zone_type_tenant_id_name")),
    )
    op.create_index(op.f("ix_zone_type_tenant_id"), "zone_type", ["tenant_id"], unique=False)
    op.create_table(
        "building",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], name=op.f("fk_building_site_id_site")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_building_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_building")),
        sa.UniqueConstraint("site_id", "code", name=op.f("uq_building_site_id_code")),
    )
    op.create_index(op.f("ix_building_site_id"), "building", ["site_id"], unique=False)
    op.create_index(op.f("ix_building_tenant_id"), "building", ["tenant_id"], unique=False)
    op.create_table(
        "catalog_item_rev",
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("rev_no", sa.Integer(), nullable=False),
        sa.Column(
            "shape",
            sa.Enum(
                "box",
                "cylinder",
                "l_shape",
                "model",
                name="catalog_shape",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("width_mm", sa.Integer(), nullable=False),
        sa.Column("depth_mm", sa.Integer(), nullable=False),
        sa.Column("height_mm", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("model_key", sa.String(length=200), nullable=True),
        sa.Column("is_seat", sa.Boolean(), nullable=False),
        sa.Column("mountable", sa.Boolean(), nullable=False),
        sa.Column("attaches_to_categories", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("footprint_blocks", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "width_mm > 0 AND depth_mm > 0 AND height_mm > 0",
            name=op.f("ck_catalog_item_rev_positive_dims"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["catalog_item.id"], name=op.f("fk_catalog_item_rev_item_id_catalog_item")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_catalog_item_rev_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_item_rev")),
        sa.UniqueConstraint("item_id", "rev_no", name=op.f("uq_catalog_item_rev_item_id_rev_no")),
    )
    op.create_index(
        op.f("ix_catalog_item_rev_item_id"), "catalog_item_rev", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_item_rev_tenant_id"), "catalog_item_rev", ["tenant_id"], unique=False
    )
    op.create_table(
        "device",
        sa.Column("asset_tag", sa.String(length=100), nullable=True),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("assigned_person_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_person_id"], ["person.id"], name=op.f("fk_device_assigned_person_id_person")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_device_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device")),
        sa.UniqueConstraint("tenant_id", "asset_tag", name=op.f("uq_device_tenant_id_asset_tag")),
    )
    op.create_index(op.f("ix_device_tenant_id"), "device", ["tenant_id"], unique=False)
    op.create_table(
        "position",
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_position_tenant_id_tenant")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["org_unit.id"], name=op.f("fk_position_unit_id_org_unit")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position")),
    )
    op.create_index(op.f("ix_position_tenant_id"), "position", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_position_unit_id"), "position", ["unit_id"], unique=False)
    op.create_table(
        "unit_manager",
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"], ["person.id"], name=op.f("fk_unit_manager_person_id_person")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_unit_manager_tenant_id_tenant")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["org_unit.id"], name=op.f("fk_unit_manager_unit_id_org_unit")
        ),
        sa.PrimaryKeyConstraint("unit_id", "person_id", name=op.f("pk_unit_manager")),
    )
    op.create_index(op.f("ix_unit_manager_tenant_id"), "unit_manager", ["tenant_id"], unique=False)
    op.create_table(
        "floor",
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("level_index", sa.Integer(), nullable=False),
        sa.Column("elevation_mm", sa.Integer(), nullable=False),
        sa.Column("default_wall_height_mm", sa.Integer(), nullable=False),
        sa.Column("origin_x_mm", sa.Integer(), nullable=False),
        sa.Column("origin_y_mm", sa.Integer(), nullable=False),
        sa.Column("published_version", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["building_id"], ["building.id"], name=op.f("fk_floor_building_id_building")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_floor_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_floor")),
        sa.UniqueConstraint(
            "building_id", "level_index", name=op.f("uq_floor_building_id_level_index")
        ),
    )
    op.create_index(op.f("ix_floor_building_id"), "floor", ["building_id"], unique=False)
    op.create_index(op.f("ix_floor_tenant_id"), "floor", ["tenant_id"], unique=False)
    op.create_table(
        "unit_membership",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=True),
        sa.Column("primary_override", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"], ["person.id"], name=op.f("fk_unit_membership_person_id_person")
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["position.id"], name=op.f("fk_unit_membership_position_id_position")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_unit_membership_tenant_id_tenant")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["org_unit.id"], name=op.f("fk_unit_membership_unit_id_org_unit")
        ),
        sa.PrimaryKeyConstraint("person_id", "unit_id", name=op.f("pk_unit_membership")),
    )
    op.create_index(
        op.f("ix_unit_membership_tenant_id"), "unit_membership", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_unit_membership_unit_id"), "unit_membership", ["unit_id"], unique=False
    )
    op.create_index(
        "uq_unit_membership_one_primary",
        "unit_membership",
        ["person_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "floor_edit_lock",
        sa.Column("floor_id", sa.Uuid(), nullable=False),
        sa.Column("holder_subject", sa.String(length=255), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["floor_id"], ["floor.id"], name=op.f("fk_floor_edit_lock_floor_id_floor")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_floor_edit_lock_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("floor_id", name=op.f("pk_floor_edit_lock")),
    )
    op.create_index(
        op.f("ix_floor_edit_lock_tenant_id"), "floor_edit_lock", ["tenant_id"], unique=False
    )
    op.create_table(
        "floor_element",
        sa.Column("floor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "wall",
                "opening",
                "column",
                "zone",
                "object",
                name="element_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["floor_id"], ["floor.id"], name=op.f("fk_floor_element_floor_id_floor")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_floor_element_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_floor_element")),
    )
    op.create_index(op.f("ix_floor_element_floor_id"), "floor_element", ["floor_id"], unique=False)
    op.create_index(
        op.f("ix_floor_element_tenant_id"), "floor_element", ["tenant_id"], unique=False
    )
    op.create_table(
        "floor_version",
        sa.Column("floor_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "draft",
                "published",
                "superseded",
                "discarded",
                name="floor_version_state",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_by", sa.String(length=255), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["floor_id"], ["floor.id"], name=op.f("fk_floor_version_floor_id_floor")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_floor_version_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_floor_version")),
        sa.UniqueConstraint(
            "floor_id", "version_no", name=op.f("uq_floor_version_floor_id_version_no")
        ),
    )
    op.create_index(op.f("ix_floor_version_floor_id"), "floor_version", ["floor_id"], unique=False)
    op.create_index(
        op.f("ix_floor_version_tenant_id"), "floor_version", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_floor_version_one_draft",
        "floor_version",
        ["floor_id"],
        unique=True,
        postgresql_where=sa.text("state = 'draft'"),
    )
    op.create_geospatial_table(
        "column_rev",
        sa.Column(
            "footprint",
            Geometry(
                geometry_type="POLYGON",
                srid=0,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("height_mm", sa.Integer(), nullable=False),
        sa.Column("element_id", sa.Uuid(), nullable=False),
        sa.Column("from_version", sa.Integer(), nullable=False),
        sa.Column("to_version", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.literal_column("element_id"), "="),
            (sa.text("int4range(from_version, to_version)"), "&&"),
            using="gist",
            name="ex_column_rev_version_overlap",
        ),
        sa.CheckConstraint(
            "ST_OrderingEquals(footprint, ST_SnapToGrid(footprint, 1))",
            name=op.f("ck_column_rev_footprint_on_grid"),
        ),
        sa.CheckConstraint("height_mm > 0", name=op.f("ck_column_rev_positive_height")),
        sa.CheckConstraint(
            "to_version IS NULL OR to_version > from_version",
            name=op.f("ck_column_rev_version_range"),
        ),
        sa.ForeignKeyConstraint(
            ["element_id"],
            ["floor_element.id"],
            name=op.f("fk_column_rev_element_id_floor_element"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_column_rev_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column_rev")),
    )
    op.create_geospatial_index(
        "idx_column_rev_footprint",
        "column_rev",
        ["footprint"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_column_rev_element_id"), "column_rev", ["element_id"], unique=False)
    op.create_index(op.f("ix_column_rev_tenant_id"), "column_rev", ["tenant_id"], unique=False)
    op.create_geospatial_table(
        "object_rev",
        sa.Column("catalog_item_rev_id", sa.Uuid(), nullable=False),
        sa.Column(
            "position",
            Geometry(
                geometry_type="POINTZ",
                srid=0,
                dimension=3,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("rotation_ddeg", sa.SmallInteger(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("attached_to_element_id", sa.Uuid(), nullable=True),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column(
            "allocation_mode",
            sa.Enum(
                "assigned",
                "bookable",
                "unavailable",
                name="allocation_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("element_id", sa.Uuid(), nullable=False),
        sa.Column("from_version", sa.Integer(), nullable=False),
        sa.Column("to_version", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.literal_column("element_id"), "="),
            (sa.text("int4range(from_version, to_version)"), "&&"),
            using="gist",
            name="ex_object_rev_version_overlap",
        ),
        sa.CheckConstraint(
            "ST_X(position) = round(ST_X(position)) AND ST_Y(position) = round(ST_Y(position)) AND ST_Z(position) = round(ST_Z(position))",
            name=op.f("ck_object_rev_position_on_grid"),
        ),
        sa.CheckConstraint(
            "rotation_ddeg >= 0 AND rotation_ddeg < 3600", name=op.f("ck_object_rev_rotation_range")
        ),
        sa.CheckConstraint(
            "to_version IS NULL OR to_version > from_version",
            name=op.f("ck_object_rev_version_range"),
        ),
        sa.ForeignKeyConstraint(
            ["attached_to_element_id"],
            ["floor_element.id"],
            name=op.f("fk_object_rev_attached_to_element_id_floor_element"),
        ),
        sa.ForeignKeyConstraint(
            ["catalog_item_rev_id"],
            ["catalog_item_rev.id"],
            name=op.f("fk_object_rev_catalog_item_rev_id_catalog_item_rev"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["device.id"], name=op.f("fk_object_rev_device_id_device")
        ),
        sa.ForeignKeyConstraint(
            ["element_id"],
            ["floor_element.id"],
            name=op.f("fk_object_rev_element_id_floor_element"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_object_rev_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_object_rev")),
    )
    op.create_geospatial_index(
        "idx_object_rev_position",
        "object_rev",
        ["position"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_object_rev_device_id"), "object_rev", ["device_id"], unique=False)
    op.create_index(op.f("ix_object_rev_element_id"), "object_rev", ["element_id"], unique=False)
    op.create_index(op.f("ix_object_rev_tenant_id"), "object_rev", ["tenant_id"], unique=False)
    op.create_table(
        "opening_rev",
        sa.Column("wall_element_id", sa.Uuid(), nullable=False),
        sa.Column(
            "opening_type",
            sa.Enum(
                "door",
                "window",
                name="opening_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("offset_mm", sa.Integer(), nullable=False),
        sa.Column("width_mm", sa.Integer(), nullable=False),
        sa.Column("height_mm", sa.Integer(), nullable=False),
        sa.Column("sill_mm", sa.Integer(), nullable=False),
        sa.Column(
            "swing",
            sa.Enum(
                "left_in",
                "left_out",
                "right_in",
                "right_out",
                "sliding",
                "none",
                name="door_swing",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("element_id", sa.Uuid(), nullable=False),
        sa.Column("from_version", sa.Integer(), nullable=False),
        sa.Column("to_version", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.literal_column("element_id"), "="),
            (sa.text("int4range(from_version, to_version)"), "&&"),
            using="gist",
            name="ex_opening_rev_version_overlap",
        ),
        sa.CheckConstraint(
            "offset_mm >= 0 AND width_mm > 0 AND height_mm > 0 AND sill_mm >= 0",
            name=op.f("ck_opening_rev_valid_dims"),
        ),
        sa.CheckConstraint(
            "to_version IS NULL OR to_version > from_version",
            name=op.f("ck_opening_rev_version_range"),
        ),
        sa.ForeignKeyConstraint(
            ["element_id"],
            ["floor_element.id"],
            name=op.f("fk_opening_rev_element_id_floor_element"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_opening_rev_tenant_id_tenant")
        ),
        sa.ForeignKeyConstraint(
            ["wall_element_id"],
            ["floor_element.id"],
            name=op.f("fk_opening_rev_wall_element_id_floor_element"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opening_rev")),
    )
    op.create_index(op.f("ix_opening_rev_element_id"), "opening_rev", ["element_id"], unique=False)
    op.create_index(op.f("ix_opening_rev_tenant_id"), "opening_rev", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_opening_rev_wall_element_id"), "opening_rev", ["wall_element_id"], unique=False
    )
    op.create_table(
        "seat_assignment",
        sa.Column("seat_element_id", sa.Uuid(), nullable=False),
        sa.Column("holder_person_id", sa.Uuid(), nullable=True),
        sa.Column("holder_unit_id", sa.Uuid(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assigned_by", sa.String(length=255), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "num_nonnulls(holder_person_id, holder_unit_id) = 1",
            name=op.f("ck_seat_assignment_exactly_one_holder"),
        ),
        sa.ForeignKeyConstraint(
            ["holder_person_id"],
            ["person.id"],
            name=op.f("fk_seat_assignment_holder_person_id_person"),
        ),
        sa.ForeignKeyConstraint(
            ["holder_unit_id"],
            ["org_unit.id"],
            name=op.f("fk_seat_assignment_holder_unit_id_org_unit"),
        ),
        sa.ForeignKeyConstraint(
            ["seat_element_id"],
            ["floor_element.id"],
            name=op.f("fk_seat_assignment_seat_element_id_floor_element"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_seat_assignment_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seat_assignment")),
        sa.UniqueConstraint("seat_element_id", name=op.f("uq_seat_assignment_seat_element_id")),
    )
    op.create_index(
        op.f("ix_seat_assignment_holder_person_id"),
        "seat_assignment",
        ["holder_person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seat_assignment_holder_unit_id"),
        "seat_assignment",
        ["holder_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seat_assignment_tenant_id"), "seat_assignment", ["tenant_id"], unique=False
    )
    op.create_geospatial_table(
        "wall_rev",
        sa.Column(
            "centerline",
            Geometry(
                geometry_type="LINESTRING",
                srid=0,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("thickness_mm", sa.Integer(), nullable=False),
        sa.Column("height_mm", sa.Integer(), nullable=False),
        sa.Column("element_id", sa.Uuid(), nullable=False),
        sa.Column("from_version", sa.Integer(), nullable=False),
        sa.Column("to_version", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.literal_column("element_id"), "="),
            (sa.text("int4range(from_version, to_version)"), "&&"),
            using="gist",
            name="ex_wall_rev_version_overlap",
        ),
        sa.CheckConstraint(
            "ST_NPoints(centerline) = 2", name=op.f("ck_wall_rev_centerline_two_points")
        ),
        sa.CheckConstraint(
            "ST_OrderingEquals(centerline, ST_SnapToGrid(centerline, 1))",
            name=op.f("ck_wall_rev_centerline_on_grid"),
        ),
        sa.CheckConstraint(
            "thickness_mm > 0 AND height_mm > 0", name=op.f("ck_wall_rev_positive_dims")
        ),
        sa.CheckConstraint(
            "to_version IS NULL OR to_version > from_version",
            name=op.f("ck_wall_rev_version_range"),
        ),
        sa.ForeignKeyConstraint(
            ["element_id"], ["floor_element.id"], name=op.f("fk_wall_rev_element_id_floor_element")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_wall_rev_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wall_rev")),
    )
    op.create_geospatial_index(
        "idx_wall_rev_centerline",
        "wall_rev",
        ["centerline"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_wall_rev_element_id"), "wall_rev", ["element_id"], unique=False)
    op.create_index(op.f("ix_wall_rev_tenant_id"), "wall_rev", ["tenant_id"], unique=False)
    op.create_geospatial_table(
        "zone_rev",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("zone_type_id", sa.Uuid(), nullable=False),
        sa.Column("parent_zone_element_id", sa.Uuid(), nullable=True),
        sa.Column(
            "boundary",
            Geometry(
                geometry_type="POLYGON",
                srid=0,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("element_id", sa.Uuid(), nullable=False),
        sa.Column("from_version", sa.Integer(), nullable=False),
        sa.Column("to_version", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.literal_column("element_id"), "="),
            (sa.text("int4range(from_version, to_version)"), "&&"),
            using="gist",
            name="ex_zone_rev_version_overlap",
        ),
        sa.CheckConstraint(
            "ST_NumInteriorRings(boundary) = 0", name=op.f("ck_zone_rev_boundary_no_holes")
        ),
        sa.CheckConstraint(
            "ST_OrderingEquals(boundary, ST_SnapToGrid(boundary, 1))",
            name=op.f("ck_zone_rev_boundary_on_grid"),
        ),
        sa.CheckConstraint(
            "to_version IS NULL OR to_version > from_version",
            name=op.f("ck_zone_rev_version_range"),
        ),
        sa.ForeignKeyConstraint(
            ["element_id"], ["floor_element.id"], name=op.f("fk_zone_rev_element_id_floor_element")
        ),
        sa.ForeignKeyConstraint(
            ["parent_zone_element_id"],
            ["floor_element.id"],
            name=op.f("fk_zone_rev_parent_zone_element_id_floor_element"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_zone_rev_tenant_id_tenant")
        ),
        sa.ForeignKeyConstraint(
            ["zone_type_id"], ["zone_type.id"], name=op.f("fk_zone_rev_zone_type_id_zone_type")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone_rev")),
    )
    op.create_geospatial_index(
        "idx_zone_rev_boundary",
        "zone_rev",
        ["boundary"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_zone_rev_element_id"), "zone_rev", ["element_id"], unique=False)
    op.create_index(op.f("ix_zone_rev_tenant_id"), "zone_rev", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_zone_rev_tenant_id"), table_name="zone_rev")
    op.drop_index(op.f("ix_zone_rev_element_id"), table_name="zone_rev")
    op.drop_geospatial_index(
        "idx_zone_rev_boundary",
        table_name="zone_rev",
        postgresql_using="gist",
        column_name="boundary",
    )
    op.drop_geospatial_table("zone_rev")
    op.drop_index(op.f("ix_wall_rev_tenant_id"), table_name="wall_rev")
    op.drop_index(op.f("ix_wall_rev_element_id"), table_name="wall_rev")
    op.drop_geospatial_index(
        "idx_wall_rev_centerline",
        table_name="wall_rev",
        postgresql_using="gist",
        column_name="centerline",
    )
    op.drop_geospatial_table("wall_rev")
    op.drop_index(op.f("ix_seat_assignment_tenant_id"), table_name="seat_assignment")
    op.drop_index(op.f("ix_seat_assignment_holder_unit_id"), table_name="seat_assignment")
    op.drop_index(op.f("ix_seat_assignment_holder_person_id"), table_name="seat_assignment")
    op.drop_table("seat_assignment")
    op.drop_index(op.f("ix_opening_rev_wall_element_id"), table_name="opening_rev")
    op.drop_index(op.f("ix_opening_rev_tenant_id"), table_name="opening_rev")
    op.drop_index(op.f("ix_opening_rev_element_id"), table_name="opening_rev")
    op.drop_table("opening_rev")
    op.drop_index(op.f("ix_object_rev_tenant_id"), table_name="object_rev")
    op.drop_index(op.f("ix_object_rev_element_id"), table_name="object_rev")
    op.drop_index(op.f("ix_object_rev_device_id"), table_name="object_rev")
    op.drop_geospatial_index(
        "idx_object_rev_position",
        table_name="object_rev",
        postgresql_using="gist",
        column_name="position",
    )
    op.drop_geospatial_table("object_rev")
    op.drop_index(op.f("ix_column_rev_tenant_id"), table_name="column_rev")
    op.drop_index(op.f("ix_column_rev_element_id"), table_name="column_rev")
    op.drop_geospatial_index(
        "idx_column_rev_footprint",
        table_name="column_rev",
        postgresql_using="gist",
        column_name="footprint",
    )
    op.drop_geospatial_table("column_rev")
    op.drop_index(
        "uq_floor_version_one_draft",
        table_name="floor_version",
        postgresql_where=sa.text("state = 'draft'"),
    )
    op.drop_index(op.f("ix_floor_version_tenant_id"), table_name="floor_version")
    op.drop_index(op.f("ix_floor_version_floor_id"), table_name="floor_version")
    op.drop_table("floor_version")
    op.drop_index(op.f("ix_floor_element_tenant_id"), table_name="floor_element")
    op.drop_index(op.f("ix_floor_element_floor_id"), table_name="floor_element")
    op.drop_table("floor_element")
    op.drop_index(op.f("ix_floor_edit_lock_tenant_id"), table_name="floor_edit_lock")
    op.drop_table("floor_edit_lock")
    op.drop_index(
        "uq_unit_membership_one_primary",
        table_name="unit_membership",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_index(op.f("ix_unit_membership_unit_id"), table_name="unit_membership")
    op.drop_index(op.f("ix_unit_membership_tenant_id"), table_name="unit_membership")
    op.drop_table("unit_membership")
    op.drop_index(op.f("ix_floor_tenant_id"), table_name="floor")
    op.drop_index(op.f("ix_floor_building_id"), table_name="floor")
    op.drop_table("floor")
    op.drop_index(op.f("ix_unit_manager_tenant_id"), table_name="unit_manager")
    op.drop_table("unit_manager")
    op.drop_index(op.f("ix_position_unit_id"), table_name="position")
    op.drop_index(op.f("ix_position_tenant_id"), table_name="position")
    op.drop_table("position")
    op.drop_index(op.f("ix_device_tenant_id"), table_name="device")
    op.drop_table("device")
    op.drop_index(op.f("ix_catalog_item_rev_tenant_id"), table_name="catalog_item_rev")
    op.drop_index(op.f("ix_catalog_item_rev_item_id"), table_name="catalog_item_rev")
    op.drop_table("catalog_item_rev")
    op.drop_index(op.f("ix_building_tenant_id"), table_name="building")
    op.drop_index(op.f("ix_building_site_id"), table_name="building")
    op.drop_table("building")
    op.drop_index(op.f("ix_zone_type_tenant_id"), table_name="zone_type")
    op.drop_table("zone_type")
    op.drop_index(op.f("ix_user_session_tenant_id"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_subject"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_expires_at"), table_name="user_session")
    op.drop_table("user_session")
    op.drop_index(op.f("ix_user_profile_tenant_id"), table_name="user_profile")
    op.drop_table("user_profile")
    op.drop_index(op.f("ix_site_tenant_id"), table_name="site")
    op.drop_table("site")
    op.drop_index(op.f("ix_person_tenant_id"), table_name="person")
    op.drop_table("person")
    op.drop_index(
        "uq_org_unit_single_root",
        table_name="org_unit",
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.drop_index(op.f("ix_org_unit_tenant_id"), table_name="org_unit")
    op.drop_index(op.f("ix_org_unit_parent_id"), table_name="org_unit")
    op.drop_table("org_unit")
    op.drop_index(op.f("ix_catalog_item_tenant_id"), table_name="catalog_item")
    op.drop_table("catalog_item")
    op.drop_index(op.f("ix_audit_event_tenant_id"), table_name="audit_event")
    op.drop_index("ix_audit_event_entity", table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_table("tenant")
    # ### end Alembic commands ###
